<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'center_id',
'name',
'description',
'address',
'city',
'postal_code',
'latitude',
'longitude',
'average_rating',
'manager_id',
'disponibilite',
'created_at',
'updated_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'center_id' => array( 'import_field' ),
'name' => array( 'import_field1' ),
'description' => array( 'import_field2' ),
'address' => array( 'import_field3' ),
'city' => array( 'import_field4' ),
'postal_code' => array( 'import_field5' ),
'latitude' => array( 'import_field6' ),
'longitude' => array( 'import_field7' ),
'average_rating' => array( 'import_field8' ),
'manager_id' => array( 'import_field9' ),
'disponibilite' => array( 'import_field10' ),
'created_at' => array( 'import_field11' ),
'updated_at' => array( 'import_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'center_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'name',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'description',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'address',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'city',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'postal_code',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'latitude',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'longitude',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'average_rating',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'manager_id',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'disponibilite',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'created_at',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'updated_at',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>